services:
  sharifhealth:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sharifhealth-app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    networks:
      - sharifhealth-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy (nginx) for production
  nginx:
    image: nginx:alpine
    container_name: sharifhealth-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - sharifhealth
    networks:
      - sharifhealth-network
    restart: unless-stopped
    profiles:
      - production

networks:
  sharifhealth-network:
    driver: bridge

volumes:
  sharifhealth-data:
